services:
  lista:  # Nombre del servicio
    container_name: Lista   # Nombre del contenedor
    image: python:3.13-slim # Imagen base
    build:
      context: .  # Contexto para la construcción
      dockerfile: Dockerfile  # Asegúrate de que el Dockerfile esté en la raíz del contexto
    environment:
      - PYTHONPATH=/CODE  
    networks:
      - Proyectos  # Conéctate a la red 'Proyectos'
    ports:
      - "8003:8003"  # Mapea el puerto 8001 del contenedor al puerto 8001 de la máquina host
    volumes:
      - .:/CODE  # Monta el directorio actual en el contenedor para desarrollo
      - lista:/CODE  # Usa el volumen existente llamado Inventario

networks:
  Proyectos:  # Define la red 'Proyectos'
    external: true  # Asegúrate de que use la red externa existente

volumes:
  lista:  # Define el volumen llamado lista